### ISSUE TITLE
jquery templates output

### ISSUE THREAD

**Issue by dadon** [garmoncheg/django_multiuploader#1]
You use a strange way to show jquery templates in django. Use the template tag verbatim - https://gist.github.com/629508, example - https://github.com/joshbohde/django-backbone-example/blob/master/backbone_example/templates/index.html

**Comment by garmoncheg** [comment]
I egree... You suggest the righter and reusable way to do that... Thanks man!
I'll implement it right now!)

**Comment by garmoncheg** [comment]
Done thanks again for idea. That way I used was the only thing I had found at Stackowerflow and went no further. This issue took it ot version 1.2!)
