### ISSUE TITLE
 Invalid block tag: 'multiupform'

### ISSUE THREAD

**Issue by cyphunk** [garmoncheg/django_multiuploader#13]
Getting this error. Installed multiuploader via pip. Added it to INSTALLED_APPS in settings.py, added the urls settings as guided in the readme, copied files from media to site media but still getting this error:

``````
File "/Users/user/projects2/hhl/auctions4/virtualenv/lib/python2.7/site-packages/django/template/base.py", line 328, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'multiupform```
``````

**Comment by cyphunk** [comment]
still investigating. might have some details wrong.

**Comment by kalkehcoisa** [comment]
Have you loaded the multiuploader template tags? {% load multiuploader %}

If still not solved, I forked the main project and made some corrections.
I've just sent a pull request (forgot to send earlier) that probably fix
this and some other problems.

On Mon, Sep 16, 2013 at 1:32 PM, Nathan Fain notifications@github.comwrote:

> still investigating. might have some details wrong.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/garmoncheg/django_multiuploader/issues/13#issuecomment-24524009
> .

## 

## 

"Não há verdadeira sabedoria sem bondade" Beethoven
"A felicidade acontece quando o que você pensa, o que você diz e o que você
faz estão em harmonia." Mahatma Gandhi

**Comment by ghost** [comment]
I am having the same issue, i had followed instructions i.e put it in installed apps, including urls, created required tables .. etc but it gives me - " Invalid block tag: 'multiupform'  ".How to resolve this ?

**Comment by abradle** [comment]
I am also having this issue. If you would like more information let me know.

Thanks

**Comment by kalkehcoisa** [comment]
Sorry for answering so late, I've been overwhelmed lately.
Please, send a traceback of your problem and a sample of the template in
which you are using the the template tag, so I can try to figure out what
is going on.

## 

Jayme Tosi Neto - Backend Developer
https://github.com/kalkehcoisa

**Comment by humanbeing** [comment]
Having the same problem. Any clues? :-)

**Comment by kartikdanidhariya** [comment]
I also having a same problem
