### ISSUE TITLE
Error: No module named multiuploader

### ISSUE THREAD

**Issue by jkennedy105** [garmoncheg/django_multiuploader#2]
I added everything to my existing django project, but I keep getting an error saying Error: No module named multiuploader

In my settings underneath installed apps i have multipuploader listed.

Do you have to install it to my virtual environment?

**Comment by garmoncheg** [comment]
No you don't! You must copy it's folder to root of your project, e.g. where settings.py is situated. Also you must copy folder multiuploader which is inside of the directory django_multiuploader.
so your directory listing should be:
- yourapp (dir)
- multiuploader (dir)
- settings.py
- manage.py

and so on...
- urls.py

**Comment by xdoctordog** [comment]
I have the same trouble and I dont know what should I do
