### ISSUE TITLE
error saying Only Post Accepted

### ISSUE THREAD

**Issue by jkennedy105** [garmoncheg/django_multiuploader#3]
I keep getting an error when I go to my url for /multi

I only get text ont he page that says "Only POST accepted."

Is there any way I can fix this and get the actual multiuploader

**Comment by garmoncheg** [comment]
Please RTFM.... Readme or wiki before posting issue... You should not use an url of multiuploader but template tag inside your existing view.
Please consider this part of docs:

## Example usage:

Adding this AJAX form to your web site is as simple, as adding this 2 tags to your template:

```
{% load multiuploader %}
{% multiupform %}
```

Also I've done a demo app repo here at my github.
It's called django_multiuploader_usage_demo.
For those who can not figure out this manual.) Also feel free to comment it on my
blog or send me a e-mail with your troubles/suggestions and usage experience...
https://github.com/garmoncheg/django_multiuploader_example_usage/
