### ISSUE TITLE
Error internal server error

### ISSUE THREAD

**Issue by jkennedy105** [garmoncheg/django_multiuploader#4]
I keep getting an internal server error. but the photos seem to be adding fine into the correct folder and everything.

**Comment by garmoncheg** [comment]
Have you installed sorl-thumbnails? What kind of server error you're gettiing with what text?
Please provide a "dpaste" of your errors... And please provide more info on when you're getting them exactly... (for e.g. when pressed uploading button or when returning json to javascript)...

**Comment by jkennedy105** [comment]
I installed sorl-thumbnails 

here are the steps I take when I get the error

I go to my page with the multi uploader. 
I click add files.
attach an image
I see a small thumb of the image and click the arrow next to it up upload 
then get red box with error that says image.jpg 6.47 KB Error: INTERNAL SERVER ERROR

If I go into the admin I see the image uploaded to the model.

**Comment by garmoncheg** [comment]
So error is showbn in javascript...
1. It seems that error with PATH. Please set settings according to docs. Set paths like told in readme.
Maybe it can not find somehow your view response. 
2. Have you installed sorl-thumbnails?
Plugin needs it and will not generate thumbnail and throw an error.

Have you tried to debug? Like with Firebug 1.8 or so... it will show you a response generated by server  side... could you provide it?

I have lots of users without problems... So it seems that problem with your exact config of the plugin instance...
