### ISSUE TITLE
django error storage module

### ISSUE THREAD

**Issue by jkennedy105** [garmoncheg/django_multiuploader#5]
Request Method:     POST
Request URL:    http://127.0.0.1:8000/multi/
Django Version:     1.3
Exception Type:     ImproperlyConfigured
Exception Value:    

multipuloader_image isn't a storage module.

Exception Location:     /Users/user/projects/venv/lib/python2.6/site-packages/django/core/files/storage.py in get_storage_class, line 260
Python Executable:  /Users/user/projects/venv/bin/python

**Comment by garmoncheg** [comment]
1. Have you done 'syncdb' after adding this app?
2. Have you enabled -777 or similar full access to photos and cache folders for your app?
   They are specified in settings BTW...

It may be some issue with using django 1.3...
I'm using 1.2.5 now. I'll try to fix this soon if it is an issue with new django version.
